name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          milestone: v0.1.0
          min_approved_reviews: 1

      - name: Test Output with Environment Variable
        id: output
        env:
          REMINDER_MSG: ${{ steps.test-action.outputs.reminder_message }}
        run: |
          echo "Testing output value..."
          if [ -z "$REMINDER_MSG" ]; then
            echo "❌ Output is empty"
            exit 1
          fi
          echo "✅ Output value: $REMINDER_MSG"
